In [ ]:
# Code snippet 0
# Installing pycaret
!pip install -U --pre pycaret

In [ ]:
# Code snippet 1
# Importing the dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/Zillow%20Tarrant%20County%20Raw%20Data.csv')

# Display the data
data

,beds,baths,sqft,Age,lot_size,property_type,exterior_walls,roof,basement,restaurants,...,beauty_spas,active_life,median_age,married,college_grad,property_tax,insurance,median_school,num_schools,Sales_price
0,1,1,584,9,0,Apartment / Condo / Townhouse,Wood Siding,NaN,0,107,...,47,58,33,65,84,234,81,9.0,3,295850
1,1,1,612,57,0,Apartment / Condo / Townhouse,Brick,Composition Shingle,1,105,...,26,14,39,73,69,169,51,3.0,3,216500
2,1,1,615,59,0,Apartment / Condo / Townhouse,Wood Siding,NaN,0,183,...,74,62,28,15,86,216,74,8.0,3,279900
3,1,1,618,22,33541,Apartment / Condo / Townhouse,Wood Siding,NaN,0,198,...,72,83,36,25,91,265,92,9.0,3,379900
4,1,1,634,30,0,Apartment / Condo / Townhouse,Brick,NaN,0,149,...,50,73,37,20,75,88,30,9.0,3,340000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,5,6,6381,18,224334,Single-Family,Stucco,Composition Shingle,1,0,...,0,1,46,76,87,1250,381,10.0,3,385000
1879,5,6,6501,66,23086,Single-Family,Brick,Composition Shingle,1,45,...,61,11,42,73,61,1553,473,9.0,3,690000
1880,5,6,7064,27,217800,Single-Family,Metal,Composition Shingle,1,5,...,1,2,43,87,66,942,287,8.0,1,600000
1881,5,6,7500,16,8886,Single-Family,Siding (Alum/Vinyl),Asphalt,1,18,...,8,6,43,61,51,803,245,5.0,2,759900
1882,5,6,7515,64,10497,Single-Family,Brick,Composition Shingle,1,0,...,0,5,37,80,86,1459,444,9.0,3,735000

In [ ]:
# Code snippet 2
# Importing clustering ML components
from pycaret.clustering import *

In [ ]:
# Code snippet 3
# Setting up pycaret configuration
cluster_model = setup(data)

In [ ]:
# Code snippet 4
# Create a clustering model using k-means ML algo
kmeans_model= create_model('kmeans')

Processing:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
# Code snippet 5
# Assigning the clusters to the datapoints
kmeans_clusters = assign_model(kmeans_model)

# Display the clusters
kmeans_clusters

In [ ]:
# Code snippet #6
# Display the cluster sizes
kmeans_clusters['Cluster'].value_counts()

Cluster
Cluster 0    614
Cluster 2    596
Cluster 1    396
Cluster 3    277
Name: count, dtype: int64