In [ ]:
# Code snippet 1
# Installing pycaret for ML modeling
!pip install -U --pre pycaret

In [ ]:
# Code snippet 2
# Importing the dataset
import pandas as pd
url = 'https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/2023%20Texas%20High%20Schools%20Scores.csv'

data = pd.read_csv(url)

data

,School,School URL,District,District URL,City,City URL,Zip,County,Phone,Is Title I,...,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Home Prices Ranking,Community Health Ranking,Standard Score
0,Lasa High School,https://www.schooldigger.com/go/TX/schools/089...,Austin Independent School District,https://www.schooldigger.com/go/TX/district/08...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78724,Travis County,(512) 414-2589,No,...,16.5,14.0,2.6,0.1,23.2,23.6,0.1,6.9,43.6,97.2
1,School For The Talented And Gifted,https://www.schooldigger.com/go/TX/schools/162...,Dallas Independent School District,https://www.schooldigger.com/go/TX/district/16...,Dallas,https://www.schooldigger.com/go/TX/city/Dallas...,75203,Dallas County,(972) 925-5970,Yes,...,17.5,32.5,8.8,0.4,15.5,41.2,0.2,2.8,31.0,96.9
2,School Of Science And Engineering,https://www.schooldigger.com/go/TX/schools/162...,Dallas Independent School District,https://www.schooldigger.com/go/TX/district/16...,Dallas,https://www.schooldigger.com/go/TX/city/Dallas...,75203,Dallas County,(972) 925-5960,Yes,...,19.7,54.0,9.9,0.2,12.5,61.6,0.6,1.0,14.2,96.6
3,Health Careers High School,https://www.schooldigger.com/go/TX/schools/331...,Northside Independent School District,https://www.schooldigger.com/go/TX/district/33...,San Antonio,https://www.schooldigger.com/go/TX/city/San+An...,78229,Bexar County,(210) 397-5400,No,...,17.8,22.2,5.2,0.1,19.3,54.4,0.3,3.1,17.6,95.5
4,Debakey H S For Health Prof,https://www.schooldigger.com/go/TX/schools/236...,Houston Independent School District,https://www.schooldigger.com/go/TX/district/23...,Houston,https://www.schooldigger.com/go/TX/city/Housto...,77030,Harris County,(713) 741-2410,Yes,...,18.4,42.9,16.8,0.5,30.0,37.1,0.4,2.0,13.1,95.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816,W B Bizzell Academy,https://www.schooldigger.com/go/TX/schools/321...,Navasota Independent School District,https://www.schooldigger.com/go/TX/district/32...,Navasota,https://www.schooldigger.com/go/TX/city/Navaso...,77868,Grimes County,(936) 825-4296,No,...,9.0,83.3,30.0,0.0,0.0,36.7,0.0,3.3,30.0,1.7
1817,Phoenix High School,https://www.schooldigger.com/go/TX/schools/183...,Elgin Independent School District,https://www.schooldigger.com/go/TX/district/18...,Elgin,https://www.schooldigger.com/go/TX/city/Elgin/...,78621,Bastrop County,(512) 281-9774,No,...,9.3,77.1,16.7,0.0,0.0,66.7,0.0,0.0,16.7,1.5
1818,Graduation Prep Academy Navarro,https://www.schooldigger.com/go/TX/schools/089...,Austin Independent School District,https://www.schooldigger.com/go/TX/district/08...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78758,Travis County,(512) 414-2896,No,...,22.7,93.4,12.1,0.0,3.3,80.2,0.0,2.2,2.2,1.3
1819,Munday,https://www.schooldigger.com/go/TX/schools/000...,University Of Texas University Charter School,https://www.schooldigger.com/go/TX/district/00...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78723,Travis County,(512) 997-8872,No,...,4.6,78.6,21.4,0.0,0.0,42.9,0.0,7.1,28.6,1.0
1820,La Feria Academy,https://www.schooldigger.com/go/TX/schools/260...,La Feria Independent School District,https://www.schooldigger.com/go/TX/district/26...,La Feria,https://www.schooldigger.com/go/TX/city/La+Fer...,78559,Cameron County,(956) 797-8360,Yes,...,8.2,90.9,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.3

In [ ]:
# Code snippet 2
# Displaying data columns
data.columns

Index(['School', 'School URL', 'District', 'District URL', 'City', 'City URL',
       'Zip', 'County', 'Phone', 'Is Title I', 'Is Charter', 'Is Magnet',
       'Is Virtual', 'Number Students', 'Number Full-time Teachers',
       'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
       'Percent Homes Rented', 'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income',
       'Home Prices Ranking', 'Community Health Ranking', 'Standard Score'],
      dtype='object')

In [ ]:
# Code snippet 3
# Setting the target variable
y = 'Standard Score'

In [ ]:
# Code snippet 4
# Setting variables to ignore(noise/redundant/feeder variables and ones that are missing more than 20% data)
ignored_cols = ['School', 'School URL', 'District URL',  'City URL',
       'Phone', 'Home Prices Ranking', 'Community Health Ranking']

In [ ]:
# Code snippet 5
# Setting the numerical columns
num_cols = ['Number Students', 'Number Full-time Teachers',
       'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
       'Percent Homes Rented', 'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income']

In [ ]:
# Code snippet 6
# Setting the categorical columns
cat_cols = ['District', 'City', 'Zip', 'County', 'Is Title I', 'Is Charter', 'Is Magnet',
       'Is Virtual']

In [ ]:
# Code snippet 7
# Importing Regression components from pycaret
from pycaret.regression import *

In [ ]:
# Code snippet 8
# Setting /configuring pycaret ML modeling
regression_setup = setup(data,
                         target = y,
                         ignore_features = ignored_cols,
                         numeric_features = num_cols,
                         categorical_features = cat_cols)

In [ ]:
# Code snippet 9
# Invoking ML algorithms
compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

HuberRegressor()

In [ ]:
# Code snippet 10
# Build the ML model using the best algo
ml_model = create_model('huber')

In [ ]:
# Code snippet 11
# Predicting standard scores using the best model
score_predictions = predict_model(ml_model, data)

# Exporting predictions to a csv file
score_predictions.to_csv('TX Standard Scores Predictions.csv')

In [ ]:
# Code snippet 12
# Importing new client data (for which std score predictions need to be made)
client_data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/TX%20High%20Schools%20-%20Client%20Data.csv')

# Displaying client data set shape
client_data.shape

(217, 21)

In [ ]:
# Code snippet 13
# Displying client data features
client_data.columns

Index(['School', 'District', 'City', 'Zip', 'County', 'Phone', 'Is Title I',
       'Is Charter', 'Is Magnet', 'Is Virtual', 'Number Students',
       'Number Full-time Teachers', 'Student/Teacher Ratio',
       'Percent Free/Disc Lunch', 'Percent Homes Rented',
       'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income',
       'Home Prices Ranking', 'Community Health Ranking'],
      dtype='object')

In [ ]:
# Code snippet 14
# Predicting standard scores using the best model for the client data
client_data_score_predictions = predict_model(ml_model, client_data)

# Exporting predictions to as csv file
client_data_score_predictions.to_csv('TX Client data Standard Scores Predictions.csv')