In [ ]:
# Assigning the data url
data_url = 'https://raw.githubusercontent.com/nvamsimohan/DallasDSA/main/2021%20Texas%20High%20Schools%20Scores.csv'
data_url

'https://raw.githubusercontent.com/nvamsimohan/DallasDSA/main/2021%20Texas%20High%20Schools%20Scores.csv'

In [ ]:
# Importing pandas package for data processing
import pandas

In [ ]:
# Reading the data from the web URL
data = pandas.read_csv(data_url)

# Displaying the data
data

,School,School URL,District,District URL,City,City URL,Zip,County,Phone,Is Title I,...,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Home Prices Ranking,Community Health Ranking,Standard Score
0,Lasa High School,https://www.schooldigger.com/go/TX/schools/089...,Austin Independent School District,https://www.schooldigger.com/go/TX/district/08...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78724,Travis County,(512) 414-2589,No,...,16.5,14.0,2.6,0.1,23.2,23.6,0.1,6.9,43.6,97.2
1,School For The Talented And Gifted,https://www.schooldigger.com/go/TX/schools/162...,Dallas Independent School District,https://www.schooldigger.com/go/TX/district/16...,Dallas,https://www.schooldigger.com/go/TX/city/Dallas...,75203,Dallas County,(972) 925-5970,Yes,...,17.5,32.5,8.8,0.4,15.5,41.2,0.2,2.8,31.0,96.9
2,School Of Science And Engineering,https://www.schooldigger.com/go/TX/schools/162...,Dallas Independent School District,https://www.schooldigger.com/go/TX/district/16...,Dallas,https://www.schooldigger.com/go/TX/city/Dallas...,75203,Dallas County,(972) 925-5960,Yes,...,19.7,54.0,9.9,0.2,12.5,61.6,0.6,1.0,14.2,96.6
3,Health Careers High School,https://www.schooldigger.com/go/TX/schools/331...,Northside Independent School District,https://www.schooldigger.com/go/TX/district/33...,San Antonio,https://www.schooldigger.com/go/TX/city/San+An...,78229,Bexar County,(210) 397-5400,No,...,17.8,22.2,5.2,0.1,19.3,54.4,0.3,3.1,17.6,95.5
4,Debakey H S For Health Prof,https://www.schooldigger.com/go/TX/schools/236...,Houston Independent School District,https://www.schooldigger.com/go/TX/district/23...,Houston,https://www.schooldigger.com/go/TX/city/Housto...,77030,Harris County,(713) 741-2410,Yes,...,18.4,42.9,16.8,0.5,30.0,37.1,0.4,2.0,13.1,95.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816,W B Bizzell Academy,https://www.schooldigger.com/go/TX/schools/321...,Navasota Independent School District,https://www.schooldigger.com/go/TX/district/32...,Navasota,https://www.schooldigger.com/go/TX/city/Navaso...,77868,Grimes County,(936) 825-4296,No,...,9.0,83.3,30.0,0.0,0.0,36.7,0.0,3.3,30.0,1.7
1817,Phoenix High School,https://www.schooldigger.com/go/TX/schools/183...,Elgin Independent School District,https://www.schooldigger.com/go/TX/district/18...,Elgin,https://www.schooldigger.com/go/TX/city/Elgin/...,78621,Bastrop County,(512) 281-9774,No,...,9.3,77.1,16.7,0.0,0.0,66.7,0.0,0.0,16.7,1.5
1818,Graduation Prep Academy Navarro,https://www.schooldigger.com/go/TX/schools/089...,Austin Independent School District,https://www.schooldigger.com/go/TX/district/08...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78758,Travis County,(512) 414-2896,No,...,22.7,93.4,12.1,0.0,3.3,80.2,0.0,2.2,2.2,1.3
1819,Munday,https://www.schooldigger.com/go/TX/schools/000...,University Of Texas University Charter School,https://www.schooldigger.com/go/TX/district/00...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78723,Travis County,(512) 997-8872,No,...,4.6,78.6,21.4,0.0,0.0,42.9,0.0,7.1,28.6,1.0
1820,La Feria Academy,https://www.schooldigger.com/go/TX/schools/260...,La Feria Independent School District,https://www.schooldigger.com/go/TX/district/26...,La Feria,https://www.schooldigger.com/go/TX/city/La+Fer...,78559,Cameron County,(956) 797-8360,Yes,...,8.2,90.9,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.3

In [ ]:
# Displaying the dataset size/shape
data.shape

(1821, 25)

In [ ]:
# Displaying the column names
data.columns

Index(['School', 'School URL', 'District', 'District URL', 'City', 'City URL',
       'Zip', 'County', 'Phone', 'Is Title I', 'Is Charter', 'Is Magnet',
       'Is Virtual', 'Number Students', 'Number Full-time Teachers',
       'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
       'Percent Homes Rented', 'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income',
       'Home Prices Ranking', 'Community Health Ranking', 'Standard Score'],
      dtype='object')

In [ ]:
# Displaying the info of columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1821 entries, 0 to 1820
Data columns (total 25 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   School                                                1821 non-null   object
 1   School URL                                            1821 non-null   object
 2   District                                              1821 non-null   object
 3   District URL                                          1821 non-null   object
 4   City                                                  1821 non-null   object
 5   City URL                                              1821 non-null   object
 6   Zip                                                   1821 non-null   int64
 7   County                                                1821 non-null   object
 8   Phone                                                 1821 non-null   object
 9   Is Title I                                            1821 non-null   object
 10  Is Charter                                            1821 non-null   object
 11  Is Magnet                                             1821 non-null   object
 12  Is Virtual                                            1821 non-null   object
 13  Number Students                                       1821 non-null   int64
 14  Number Full-time Teachers                             1811 non-null   float64
 15  Student/Teacher Ratio                                 1810 non-null   float64
 16  Percent Free/Disc Lunch                               1821 non-null   float64
 17  Percent Homes Rented                                  1821 non-null   float64
 18  Percent of Unemployment                               1821 non-null   float64
 19  Percent Parents with Masters and above education      1821 non-null   float64
 20  Percent parents with less than High School education  1821 non-null   float64
 21  Percent Home Incomes with less than Median income     1821 non-null   float64
 22  Home Prices Ranking                                   1049 non-null   float64
 23  Community Health Ranking                              804 non-null    float64
 24  Standard Score                                        1821 non-null   float64
dtypes: float64(11), int64(2), object(12)
memory usage: 355.8+ KB

In [ ]:
# Displaying statistical descriptive summary of numerical variables
data.describe()

,Zip,Number Students,Number Full-time Teachers,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Home Prices Ranking,Community Health Ranking,Standard Score
count,1821.000000,1821.000000,1811.000000,1810.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1049.000000,804.000000,1821.000000
mean,77315.758375,916.175728,61.561016,13.560939,59.395936,10.565678,0.358210,2.416804,49.242394,0.107194,2.013632,25.547512,47.299890
std,1437.680272,992.964357,57.729077,4.968011,24.166854,13.997171,0.775274,6.184342,28.704876,0.464306,2.191142,25.982462,25.110679
min,75002.000000,0.000000,0.000000,0.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.300000
25%,76063.000000,205.000000,19.600000,10.300000,41.700000,1.000000,0.000000,0.000000,24.700000,0.000000,0.400000,2.800000,27.000000
50%,77358.000000,456.000000,36.200000,13.400000,60.000000,5.000000,0.200000,0.500000,45.000000,0.000000,1.500000,15.050000,48.500000
75%,78570.000000,1476.000000,96.350000,16.100000,79.400000,14.700000,0.500000,1.700000,74.200000,0.100000,3.000000,42.850000,67.700000
max,79938.000000,10450.000000,288.600000,80.000000,100.000000,97.300000,22.000000,84.600000,100.000000,15.700000,25.000000,93.700000,97.200000

In [ ]:
# Code snippet 7
# Displaying the column names
data.columns

Index(['School', 'School URL', 'District', 'District URL', 'City', 'City URL',
       'Zip', 'County', 'Phone', 'Is Title I', 'Is Charter', 'Is Magnet',
       'Is Virtual', 'Number Students', 'Number Full-time Teachers',
       'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
       'Percent Homes Rented', 'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income',
       'Home Prices Ranking', 'Community Health Ranking', 'Standard Score'],
      dtype='object')

In [ ]:
# Code snippet 8
# Creating predictors variable
predictors = ['District',  'City',
       'Zip', 'County', 'Is Title I', 'Is Charter', 'Is Magnet',
       'Is Virtual', 'Number Students', 'Number Full-time Teachers',
       'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
       'Percent Homes Rented', 'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income',
       'Standard Score']

# Creating a subset of data with only predictor columns
data_pred = data[predictors]

#Displaying the pred_data columns
data_pred.columns

Index(['District', 'City', 'Zip', 'County', 'Is Title I', 'Is Charter',
       'Is Magnet', 'Is Virtual', 'Number Students',
       'Number Full-time Teachers', 'Student/Teacher Ratio',
       'Percent Free/Disc Lunch', 'Percent Homes Rented',
       'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income', 'Standard Score'],
      dtype='object')

In [ ]:
# Code snippet 9
# Displaying the size of the predictors dataset
data_pred.shape

(1821, 18)

In [ ]:
# Code snippet 10
# Installing Pycaret ML package
!pip install -U --pre pycaret

In [ ]:
# Code snippet 11
# Importing the regression components of pycaret
from pycaret.regression import *

In [ ]:
# Code snippet 12
# Storing all categorical columns in a variable
cat_cols = ['District', 'City', 'Zip', 'County', 'Is Title I', 'Is Charter',
       'Is Magnet', 'Is Virtual']

In [ ]:
# Code snippet 13
# Storing all numerical columns in a variable
num_cols = ['Number Students',
       'Number Full-time Teachers', 'Student/Teacher Ratio',
       'Percent Free/Disc Lunch', 'Percent Homes Rented',
       'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income']

In [ ]:
# Code snippet 14
# Defining the target variable
y = 'Standard Score'

In [ ]:
# Code snippet 15
# Setting up the Pycaret regression experiment
regression_model_setup = setup(data_pred,
                               target  = y,
                               categorical_features = cat_cols,
                               numeric_features= num_cols)

In [ ]:
# Code snippet 16
# Creating an ML Model using the best algorithm
best_model = compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

In [ ]:
# Code snippet 17
# Importing the client data to make predictions
import pandas as pd
client_data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/main/TX%20High%20Schools%20-%20Client%20Data.csv')
client_data.columns

Index(['School', 'District', 'City', 'Zip', 'County', 'Phone', 'Is Title I',
       'Is Charter', 'Is Magnet', 'Is Virtual', 'Number Students',
       'Number Full-time Teachers', 'Student/Teacher Ratio',
       'Percent Free/Disc Lunch', 'Percent Homes Rented',
       'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income',
       'Home Prices Ranking', 'Community Health Ranking'],
      dtype='object')

In [ ]:
# Code snippet 18
# Predicting the standard scores for the client dataset
client_data_predictions = predict_model(best_model, data = client_data)